// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PPC.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231103041548_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUtilizada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("precioCompra")
                        .HasColumnType("REAL");

                    b.Property<double>("precioVenta")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Leche",
                            Existencia = 200,
                            precioCompra = 8.0,
                            precioVenta = 15.0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pan",
                            Existencia = 200,
                            precioCompra = 15.0,
                            precioVenta = 30.0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Huevos",
                            Existencia = 200,
                            precioCompra = 10.0,
                            precioVenta = 25.0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Arroz",
                            Existencia = 200,
                            precioCompra = 25.0,
                            precioVenta = 50.0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Pasta",
                            Existencia = 200,
                            precioCompra = 30.0,
                            precioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Frutas",
                            Existencia = 200,
                            precioCompra = 30.0,
                            precioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripcion = "Verduras",
                            Existencia = 200,
                            precioCompra = 25.0,
                            precioVenta = 50.0
                        },
                        new
                        {
                            ProductoId = 8,
                            Descripcion = "Carne",
                            Existencia = 200,
                            precioCompra = 50.0,
                            precioVenta = 100.0
                        },
                        new
                        {
                            ProductoId = 10,
                            Descripcion = "Pescado",
                            Existencia = 200,
                            precioCompra = 40.0,
                            precioVenta = 80.0
                        },
                        new
                        {
                            ProductoId = 11,
                            Descripcion = "Aceite de oliva",
                            Existencia = 200,
                            precioCompra = 35.0,
                            precioVenta = 70.0
                        },
                        new
                        {
                            ProductoId = 12,
                            Descripcion = "Yogurt",
                            Existencia = 200,
                            precioCompra = 30.0,
                            precioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 13,
                            Descripcion = "Queso",
                            Existencia = 200,
                            precioCompra = 40.0,
                            precioVenta = 80.0
                        },
                        new
                        {
                            ProductoId = 14,
                            Descripcion = "Mantequilla",
                            Existencia = 200,
                            precioCompra = 30.0,
                            precioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 15,
                            Descripcion = "Galletas",
                            Existencia = 200,
                            precioCompra = 20.0,
                            precioVenta = 40.0
                        },
                        new
                        {
                            ProductoId = 16,
                            Descripcion = "Cereal",
                            Existencia = 200,
                            precioCompra = 25.0,
                            precioVenta = 50.0
                        },
                        new
                        {
                            ProductoId = 17,
                            Descripcion = "Jugo",
                            Existencia = 200,
                            precioCompra = 20.0,
                            precioVenta = 40.0
                        },
                        new
                        {
                            ProductoId = 18,
                            Descripcion = "Refresco",
                            Existencia = 200,
                            precioCompra = 20.0,
                            precioVenta = 40.0
                        },
                        new
                        {
                            ProductoId = 19,
                            Descripcion = "Cerveza",
                            Existencia = 200,
                            precioCompra = 20.0,
                            precioVenta = 40.0
                        },
                        new
                        {
                            ProductoId = 20,
                            Descripcion = "Vino",
                            Existencia = 200,
                            precioCompra = 30.0,
                            precioVenta = 60.0
                        },
                        new
                        {
                            ProductoId = 21,
                            Descripcion = "Café",
                            Existencia = 200,
                            precioCompra = 20.0,
                            precioVenta = 40.0
                        },
                        new
                        {
                            ProductoId = 22,
                            Descripcion = "Azúcar",
                            Existencia = 200,
                            precioCompra = 15.0,
                            precioVenta = 30.0
                        },
                        new
                        {
                            ProductoId = 23,
                            Descripcion = "Sal",
                            Existencia = 200,
                            precioCompra = 10.0,
                            precioVenta = 20.0
                        },
                        new
                        {
                            ProductoId = 24,
                            Descripcion = "Papel Higienico",
                            Existencia = 200,
                            precioCompra = 15.0,
                            precioVenta = 30.0
                        });
                });

            modelBuilder.Entity("EntradasDetalle", b =>
                {
                    b.HasOne("Entradas", null)
                        .WithMany("entradasDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entradas", b =>
                {
                    b.Navigation("entradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
